### PR TITLE
Fix the 'Sync stock from Square' and 'Sync inventory' links on the edit product screen.

### LINKED ISSUE #104: "Sync stock from Square" on the edit product screen is not working when Square is the SOR.
### Describe the bug
While conducting quick testing on #103, I encountered an issue: "Sync stock from Square" on the edit product screen is not functioning when Square is the SOR. It appears to work fine when WooCommerce is the SOR.

### To reproduce
1. Set up the Square plugin and enable sync with inventory sync enabled.
1. Set "Square" as the SOR.
1. Navigate to edit a Square-synced product.
1. Go to the "Inventory" tab of product data and click the "Sync stock from Square" link.
1. Notice that nothing happens.
1. Change the SOR to "WooCommerce."
1. Click the "Sync stock from Square" link on the edit product screen and observe that it appears to work fine.

**Screenshots**
Screenshot 2024-04-16 at 6 25 45 PM

### Expected behavior
Click "Sync stock from Square" on the edit product screen should sync the inventory with Square.

**Environment (please complete the following information):**
 - WordPress Version: 6.5
 - WooCommerce Version: 8.7.0
 - WooCommerce Square Plugin Version: 4.6.1
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
As reported in issue #104, the 'Sync stock from Square' and 'Sync inventory' links on the edit product screen are not working when Square is the SOR. After investigating, I discovered that this issue occurred because the event handler JavaScript code was accidentally removed by pull request https://github.com/woocommerce/woocommerce-square-private/pull/1086. This pull request restores the JavaScript code to ensure that the links work on the edit product screen.

Closes #104 

### Steps to test the changes in this Pull Request:
1. Set up the Square plugin and enable sync with inventory sync enabled.
1. Set "Square" as the SOR.
1. Navigate to edit a Square-synced product.
1. Go to the "Inventory" tab of product data and click the "Sync stock from Square" or "Sync inventory" link. (The "Sync stock from Square" link should be there for the products with inventory tracking enabled and "Sync inventory" link will be available for the product that has inventory tracking disabled)
1. Verify that both links are working as expected now

### CODE REVIEW

**Comment by iamdharmesh** [comment]
**Note:**

E2E tests are failing, but they are not related to this PR. Upon investigation, it was found that they are also failing on the `trunk`. On quick check didn't figured out the exact reason, but it is due to some errors on the block checkout. As we already have an open PR for the E2E tests, not making any changes here.

**Review by dkotter — APPROVED** [review]

**Comment by dkotter** [comment]
This can go to UAT once QA passes

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------

I have checked this issue in the `enhancement/104` branch and the related issue is resolved and working as expected.


**Testing Environment** 

<Details>

- WordPress: 6.5.3
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.8.3
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>


https://github.com/woocommerce/woocommerce-square/assets/67687255/7dd4f27c-16ee-4f94-9a50-356f6d44f61c


Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for UAT
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [x] Yes
- [ ] Not Required/Applicable for this PR

**Review by qasumitbagthariya — APPROVED** [review]

**Comment by jeffpaul** [comment]
Updated e2e tests pass, so I'm moving this along to UAT Approved.

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.5.4
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.2
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: smoke-testing

</Details>


Next Step- Ready to Merge 🚀

**Pull request merged**
