### PR TITLE
Add tracks for onboarding

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

This PR adds event tracking for onboarding.

### Tracking areas

image

Tracks the Next button, with the toggles being properties, so we can tell what features are being activated in the flow.

---

image

Tracks the X (exit wizard), with the property of Source so we can tell where in the flow, they are abandoning the onboarding wizard.

---

image

Tracks all of these options on click.

---

image

Tracks hiding express pay buttons

---

image

Track selection of all options/settings here.

---

image

Tracks enabling sandbox mode.

### Testing

Utilize Jorge Torres’ [plugin](https://gist.github.com/jorgeatorres/cd450223c16321b54ac752f0d6891dd7) that captures any requests to the Tracks endpoint and logs them locally.  This can be used to confirm events and their properties are being sent even without access to Tracks.

### CODE REVIEW

**Comment by vikrampm1** [comment]
@Sidsector9 is this ready for review?

**Comment by Sidsector9** [comment]
@vikrampm1 was waiting for some confirmation from Woo. I've raised a review request 👍

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 
-------------

I have checked the event tracking for onboarding on the **nux-tracking** branch. 


**Enable Payment methods**
image

**Configure sync setting**
image

image

**Manage payments**
image

**Advance setting and Sandbox settings**
image
image

**Manage digital wallet settings (Hide digital wallet - Apple)**
image

**Configure sandbox setting**
image


**Testing Environment** 

<Details>

- WordPress: 6.5.3
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.1
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>


**Note:**
As discussed internally with @Sidsector9 will work on **import products**, I'll approve the PR once the import products event tracking work is done.

**Comment by qasumitbagthariya** [comment]
### QA Update ✅

Thank you @Sidsector9 

Import products event tracking  ✅

image

Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [x] Yes
- [ ] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Review by diegocurbelo — APPROVED** [review]
The code looks great, and it tests well... (the new onboarding looks awesome btw 👏🏼)

In addition to the logs, I also checked the events in our tracks app:
Screenshot 2024-06-10 at 7 32 42 PM

**Comment by jeffpaul** [comment]
@slash1andy @johndcoy FYI on the above in case you have any desired changes

**Comment by dkotter** [comment]
@Sidsector9 There's a handful of merge conflicts here, I think due to [eslint changes](https://github.com/woocommerce/woocommerce-square/pull/123) that have recently been merged. Can you fix these up?

**Comment by faisal-alvi** [comment]
@Sidsector9 I've resolved the conflicts and fixed the ESLint issues. Please review it and let me know if everything looks good. Also, we should merge PR into `wizard_page` (#105) just like we did for `wizard_page_extras` (#145). This way, we will have a single main PR for NUX, which we can then merge into the smoke/regression testing branches for @qasumitbagthariya to test.

**Comment by Sidsector9** [comment]
@faisal-alvi I think we should wait for #105 to be reviewed and approved first before merging this into it. @dkotter what would you suggest?

**Comment by dkotter** [comment]
@Sidsector9 #105 has been approved and is waiting for Regression Testing (along with this PR). I've already merged both branches to `smoke-testing` so at this point, no real reason to merge this PR into `wizard_page` but that said, we'll obviously want to get this merged into `wizard_page` before we merge `wizard_page` into `trunk`

**Comment by slash1andy** [comment]
> @slash1andy @johndcoy FYI on the above in case you have any desired changes

This looks amazing, and tests well. I’m super excited for the awesome new flow and the data collected to improve. 🎉

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.5.4
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 9.0.1
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: smoke-testing

</Details>


Next Step- Ready to Merge 🚀

**Pull request merged**
