### PR TITLE
Release/4.8.0

### LINKED ISSUE #203: Release version 4.8.0
This issue is for tracking the 4.8.0 release. Target release date: **August 26 2024**

## Pre-release steps

- [x] Resolve conflicts & merge #72         
- [x] Merge #191      
- [x] Merge #183    
- [x] Merge #185  
- [x] Merge #188  
- [x] Merge #186
- [x] Merge #197 
- [x] Merge #201    
   
## Release steps

- [x] Branch: Starting from `trunk`, cut a release branch named `release/4.8.0`
- [x] Version bump: Bump the version number in `woocommerce-square.php`, `package.json`, `package-lock.json` and `readme.txt` to 4.8.0. In `woocommerce-square.php` update both the plugin "Version:" property and the plugin `WC_SQUARE_VERSION` constant
- [x] Update `@since`: Find all new `@since x.x.x` / `@since n.e.x.t` lines and update those with the new version number, 4.8.0
- [x] Generate changelog: Locally, generate the changelog by running the following Woorelease command: `php woorelease.phar cl:generate --product_version=4.8.0 https://github.com/woocommerce/woocommerce-square/tree/trunk`. Ensure the changelog updates look correct
- [x] Update changelog: Take the changelog generated from the previous step and update the release PR with those changes, both in the `changelog.txt` file and `readme.txt` file
- [x] Open PR: Open a new PR against `trunk` from the release branch, `release/4.8.0`
- [x] Run tests: On this release PR, add the label `needs: qit default tests` and `needs: e2e testing`. This will trigger the default QIT tests (activation, API and E2E) and our E2E tests. Ensure these tests pass as well as all other applicable tests
- [x] Merge: Merge the release PR into `trunk`
- [x] Prepare ZIP: Prepare the zip by running Woorelease locally on the `trunk` branch: `php woorelease.phar build https://github.com/woocommerce/woocommerce-square/tree/trunk`. Make sure you are running the proper versions of `node`, `npm` and `composer` to ensure the built files are consistent across releases. Versions can be found in [`package.json`](https://github.com/woocommerce/woocommerce-square/blob/trunk/package.json)
- [x] Compare: Download the latest [released zip](https://github.com/woocommerce/woocommerce-square/releases) and then run a diff compare against the generated zip, ensuring all expected changes are there (and no unexpected changes)
- [x] Test ZIP: Take the ZIP generated from the previous step and test this locally, ensuring version numbers look correct, the changelog looks correct and the plugin installs and activates properly
- [x] Attach ZIP: Attach the ZIP to this issue and ping the Automattic team in the `#a8c-10up-woo-support` channel to complete the release

### PR DESCRIPTION
**Pull request by dkotter**
### Changes proposed in this Pull Request:

Version bump and prep for the 4.8.0 release

Closes #203 

### Steps to test the changes in this Pull Request:

Verify all file changes look accurate

### CODE REVIEW

**Comment by dkotter** [comment]
We have one failing E2E test here that needs looked at. I retried the tests a few times but that particular test failed each time

**Review by vikrampm1 — APPROVED** [review]

**Comment by vikrampm1** [comment]
@iamdharmesh there is one failed E2E test here. Could you please review and fix it so we can unblock the release? Thanks.

**Comment by iamdharmesh** [comment]
The failing test is a newly added test in PR https://github.com/woocommerce/woocommerce-square/pull/72 (it is failing there as well). Checking on it.

**Comment by iamdharmesh** [comment]
While checking and fixing the tests, I noticed that the toggle for enabling/disabling stock management is not working in the new product editor. I'm not sure if this is related to the WC 9.2 updates. @Sidsector9 @qasumitbagthariya could you please help to check at your end to confirm the issue? 

Screenshot 2024-08-28 at 11 57 32 AM


Thank you.

**Comment by qasumitbagthariya** [comment]
@iamdharmesh 

I've cross-checked with different WooCommerce versions, 9.1.4 and 9.2.3, and confirmed the issue with version 9.2.3.


WooCommerce versions 9.1.4  ✅

https://github.com/user-attachments/assets/04b26124-217d-43a8-9bbc-2f265c8e26bb

WooCommerce versions 9.2.3  ⚠️

https://github.com/user-attachments/assets/ebb0242c-ba1b-4711-9122-82333e84a7ec

**Comment by Sidsector9** [comment]
@qasumitbagthariya I have pushed fixes, can you check?

**Comment by qasumitbagthariya** [comment]
@Sidsector9 Thanks for the fix.

I've cross-checked with WooCommerce version **9.2.3**, and enabling/disabling stock management is now working correctly with the new product editor.

I tested the following on this branch: 
stock management - new product editor ✅
stock management - Old product editor ✅

WooCommerce version 9.2.3

https://github.com/user-attachments/assets/ef56a03b-6e82-40ce-8692-e4b537a3742c


WooCommerce version 9.1.4


https://github.com/user-attachments/assets/0b5d379f-f8a6-4057-be51-4218b8d0acf5

**Comment by dkotter** [comment]
@Sidsector9 @iamdharmesh Just following up on what is left to get this release unblocked? Seems E2E tests are still failing but looks like we fixed the other issue found but just wondering if there are other things that need addressed?

**Comment by iamdharmesh** [comment]
@dkotter I found that issue while investigating the root cause of the failing E2E tests and @Sidsector9 fixed the reported issue, but the E2E test action is still failing. I think it would be best to review and fix the E2E tests. @Sidsector9, Please let me know if you want me to check the E2E test failures here.

**Comment by Sidsector9** [comment]
@iamdharmesh @dkotter I'll look into it tomorrow 👍

**Comment by Sidsector9** [comment]
@dkotter the CashApp tests are failing on Woo 9.3.0-beta.1 but passes for Woo 9.2.3. (Couldn't figure out the reason)
- I have fixed an E2E test related to the new Product Block editor. 
- @iamdharmesh will be looking into the CashApp tests as it requires more investigation.

**Comment by iamdharmesh** [comment]
@dkotter @vikrampm1 This is unblocked now.

**Comment by dkotter** [comment]
@iamdharmesh I pushed a commit up to change the release date and tests are failing again 😢 Tried running them a couple times to see if it was just a flaky test but always failed

**Comment by iamdharmesh** [comment]
> @iamdharmesh I pushed a commit up to change the release date and tests are failing again 😢 Tried running them a couple times to see if it was just a flaky test but always failed

@dkotter, this is a bit strange. I'm unable to download the artifact from the failure to determine the root cause, but in my latest commit, a few tests failed twice and are now passing (I tried two times: [1](https://github.com/woocommerce/woocommerce-square/actions/runs/10881658990/attempts/3?pr=204), [2](https://github.com/woocommerce/woocommerce-square/actions/runs/10881658990?pr=204))—and that’s without making any code changes. So, that seems flaky tests, I suspect this might be due to a sandbox issue. I noticed [this](https://discord.com/channels/1023038191151882261/1083862242811981854/1284283770513395813) message about degraded performance on the Square Discord. I’ll keep an eye on the tests for PRs to better understand the issue, but for now, I feel we’re good to proceed with the next steps here.

**Pull request merged**
