### PR TITLE
Fix fatal error when running incompatible version of WooCommerce.

### LINKED ISSUE #135: Reports of "class 'WooCommerce\Square\Gateway\Blocks_Handler' not found" fatal errors
### Describe the bug

We've received internal reports of some sites we manage getting the following fatal error:

```
PHP Fatal error:  Uncaught Error: Class "WooCommerce\Square\Gateway\Blocks_Handler" not found
in .../plugins/woocommerce-square/woocommerce-square.php:430
```

After looking into this, I found that we're init'ing our blocks handler code and our autoloader behind two different conditions, which results in cases where `register_payment_method_block_integrations()` is trying to call `new WooCommerce\Square\Gateway\Blocks_Handler()` without our autoloader existing.

For instance:

- Registering our blocks handler requires `is_environment_compatible()` to pass which checks for PHP 7.4+
- Init'ing our autoloader requires `is_environment_compatible()` + `plugins_compatible()` which also checks that WP version is 6.3+ and WC version is 8.7+.

What this difference means is if a store has WooCommerce 8.6 installed (an unsupported version), the autoloader won't be init'ed, however, the block handler code will still try to register our block integration classes resulting in the fatal error.

### To reproduce

1. Install and activate WooCommerce 8.6 and the latest WooCommerce Square
1. Load any WP Admin page
1. Note the fatal error: 
image

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - WooCommerce Square Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Modify the bootstrapping of the plugin to include compatibility checks for:
* PHP Version (existing)
* OPcache config (existing)
* WooCommerce version (new/expanded)
* WordPress version (new/expanded)

`WooCommerce_Square_Loader::add_plugin_notices()` and `WooCommerce_Square_Loader::plugins_compatible()` are deprecated in favour of the `WooCommerce_Square_Loader::is_environment_compatible()` method. This ensures that all paths for bootstrapping the extension are using the same checks.

The HPOS compatibility declaration is modified to bypass the environment check to avoid false incompatibility warnings on old versions of WooCommerce. While not related to the fatal error it is related to the various warnings not working as expected.

TODO:

* [ ] Update all instances of version `x.x.x` with the version number this is to be released in. 

Closes #135 .

### Steps to test the changes in this Pull Request:

1. Install the latest version of WordPress
2. Install and activate WooCommerce 8.6.1
3. Install and activate WooCommerce Square from this branch
4. A notice should be displayed warning the extension is disabled (on trunk a fatal error is triggered). The notice will indicate WooCommerce requires an upgrade.
5. Downgrade WordPress to 6.2.4 ([zip download here](https://github.com/WordPress/WordPress/archive/refs/tags/6.2.5.zip))
6. Reload the WP Dashboard
7. The notice should indicate both WordPress and WooCommerce require an upgrade

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ❌ 
---

@peterwilsoncc 

Even though I am using WooCommerce 8.9.1, the most latest version, I still see the warning. 

Additionally, I have a suggestion that the warning notice `WooCommerce is not installed` might be confusing to customers. 


**Warning**

> All features in Square for WooCommerce have been disabled due to unsupported settings:
• WooCommerce is not installed: The plugin requires WooCommerce version 8.7 or later be installed.

image

**Comment by peterwilsoncc** [comment]
Thanks @qasumitbagthariya, I've pushed 8fc4517dab1f8f560b23d47eee197f83bf8f946b to ensure the order of operations is correct and the `WC_VERSION` constant is defined when the environment is checked.

**Comment by qasumitbagthariya** [comment]
Thanks for the changes @peterwilsoncc 


1. Woocommerce 8.6.1, WordPress 6.5.3 ✅
image

>5. Downgrade WordPress to 6.2.4 ([zip download here](https://github.com/WordPress/WordPress/archive/refs/tags/6.2.5.zip))
6.Reload the WP Dashboard
7.The notice should indicate both WordPress and WooCommerce require an upgrade

2. I tested your given steps with WordPress 6.2.4 and WooCommerce 8.6.1, It's getting error while installing because the minimum version can't match. @peterwilsoncc is it ok? or need to check in another version? ⚠️
image

3. In the warning message the [download the minimum required version »](https://downloads.wordpress.org/plugin/woocommerce.8.7.zip) Link is not reachable, Can you please check from your end ? ❌

wrong link

**Comment by peterwilsoncc** [comment]
@qasumitbagthariya Good catch, I've pushed 6d2cf698a3a94371cbc970195377110683500f62 to normalize the version string to match how releases are tagged on WordPress.org. I suspect the broken links have been around for a while and may affect other extensions too.

**Comment by peterwilsoncc** [comment]
@dkotter Are you able to take a look at the changes since your approval:

* https://github.com/woocommerce/woocommerce-square/commit/8fc4517dab1f8f560b23d47eee197f83bf8f946b : Fixes display of notice in supported versions
* https://github.com/woocommerce/woocommerce-square/commit/6d2cf698a3a94371cbc970195377110683500f62 : Normalizes download links.

**Comment by peterwilsoncc** [comment]
> 2\. I tested your given steps with WordPress 6.2.4 and WooCommerce 8.6.1, It's getting error while installing because the minimum version can't match. @peterwilsoncc is it ok? or need to check in another version?

This is expected on older versions of WP when the latest version of WooCommerce requires a later version of WP. Unfortunately it's not something we can check before showing the notice as the message is generated via the WordPress.org plugins API.

**Comment by qasumitbagthariya** [comment]
> @qasumitbagthariya Good catch, I've pushed [6d2cf69](https://github.com/woocommerce/woocommerce-square/commit/6d2cf698a3a94371cbc970195377110683500f62) to normalize the version string to match how releases are tagged on WordPress.org. I suspect the broken links have been around for a while and may affect other extensions too.

### QA Update ✅ 

Thanks @peterwilsoncc 

Now the download link works properly, and is downloading the minimum version 👍 

**Testing Environment** 

<Details>

- WordPress: 6.5.3
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.1
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- 

</Details>

**Review by dkotter — APPROVED** [review]

**Review by qasumitbagthariya — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.


**Testing Environment** 

<Details>

- WordPress: 6.5.4
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.3
- WooCommerce - 8.6.1
- PHP: 8.3.3
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: smoke-testing

 </Details>


Next Step- Ready to Merge 🚀

**Pull request merged**
