### PR TITLE
Release/4.6.3

### LINKED ISSUE #154: Release version 4.6.3
This issue is for tracking the 4.6.3 release. Target release date: **June 17 2024**

## Pre-release steps

- [x] Resolve conflits & merge #123     
- [x] Resolve conflits & merge #131     
- [x] Merge #103  
- [x] Merge #126 
- [x] Merge #107      
- [x] Merge #124 
- [x] Merge #132 
- [x] Merge #137 
- [x] Merge #138 
 
## Release steps

- [x] Branch: Starting from `trunk`, cut a release branch named `release/4.6.3`
- [x] Version bump: Bump the version number in `woocommerce-square.php`, `package.json`, `package-lock.json` and `readme.txt` to 4.6.3. In `woocommerce-square.php` update both the plugin "Version:" property and the plugin `WC_SQUARE_VERSION` constant
- [x] Update `@since`: Find all new `@since x.x.x` / `@since n.e.x.t` lines and update those with the new version number, 4.6.3
- [x] Generate changelog: Locally, generate the changelog by running the following Woorelease command: `php woorelease.phar cl:generate --product_version=4.6.3 https://github.com/woocommerce/woocommerce-square/tree/trunk`. Ensure the changelog updates look correct
- [x] Update changelog: Take the changelog generated from the previous step and update the release PR with those changes, both in the `changelog.txt` file and `readme.txt` file
- [x] Open PR: Open a new PR against `trunk` from the release branch, `release/4.6.3`
- [x] Run tests: On this release PR, add the label `needs: qit default tests` and `needs: e2e testing`. This will trigger the default QIT tests (activation, API and E2E) and our E2E tests. Ensure these tests pass as well as all other applicable tests
- [x] Merge: Merge the release PR into `trunk`
- [x] Prepare ZIP: Prepare the zip by running Woorelease locally on the `trunk` branch: `php woorelease.phar build https://github.com/woocommerce/woocommerce-square/tree/trunk`. Make sure you are running the proper versions of `node`, `npm` and `composer` to ensure the built files are consistent across releases. Versions can be found in [`package.json`](https://github.com/woocommerce/woocommerce-square/blob/trunk/package.json)
- [x] Compare: Download the latest [released zip](https://github.com/woocommerce/woocommerce-square/releases) and then run a diff compare against the generated zip, ensuring all expected changes are there (and no unexpected changes)
- [x] Test ZIP: Take the ZIP generated from the previous step and test this locally, ensuring version numbers look correct, the changelog looks correct and the plugin installs and activates properly
- [x] Attach ZIP: Attach the ZIP to this issue and ping the Automattic team in the `#a8c-10up-woo-support` channel to complete the release

### PR DESCRIPTION
**Pull request by dkotter**
### Changes proposed in this Pull Request:

Version bump and prep for the 4.6.3 release

Closes #154 

### Steps to test the changes in this Pull Request:

Verify all file changes look accurate

### CODE REVIEW

**Comment by dkotter** [comment]
Tests are failing here and with the amount of changes in this release, would be great to get those fixed before we proceed with this release

**Review by vikrampm1 — APPROVED** [review]

**Comment by vikrampm1** [comment]
@peterwilsoncc if you can help review the failed e2e tests here when you come online next week that would be great, so we can get this release out asap.

**Comment by peterwilsoncc** [comment]
Am I correct in thinking this is the diff for the release? https://github.com/woocommerce/woocommerce-square/compare/0d8387e93f22e94e046e078ac966bc4e3ac47456...a36b601a08f5a25d841214e46716ca521853b7c8

I'll look in to this in the mean time.

**Comment by dkotter** [comment]
> Am I correct in thinking this is the diff for the release? https://github.com/woocommerce/woocommerce-square/compare/0d8387e93f22e94e046e078ac966bc4e3ac47456...a36b601a08f5a25d841214e46716ca521853b7c8

I believe that is correct, yes

**Comment by iamdharmesh** [comment]
**Note:** We already have PR raised with fixed tests https://github.com/woocommerce/woocommerce-square/pull/152.

However, some of newly added subscriptions related tests are failing in that PR, that is due to some subscriptions plugin setup issue in GH action. But existing tests are passing as expected.

**Comment by dkotter** [comment]
@iamdharmesh So seems like getting #152 finished up and merged in is the best next step here, does that sound correct? Just don't want to spend time fixing tests here if they've already been (mostly) fixed in that PR

**Comment by iamdharmesh** [comment]
> @iamdharmesh So seems like getting https://github.com/woocommerce/woocommerce-square/pull/152 finished up and merged in is the best next step here, does that sound correct? Just don't want to spend time fixing tests here if they've already been (mostly) fixed in that PR

Yes, Correct @dkotter.

**Pull request merged**
