### PR TITLE
Display ApplePay on block cart and block checkout.

### LINKED ISSUE #113: Apple Pay not showing even when domain is verified
### Describe the bug

We've encountered an issue on the site https://support2enhance.co.uk whereby Apple Pay isn't showing, but Google Pay does show. This was tested both on Mac Safari and iPhone devices.

Logs from the merchant's site show that their domain is already verified with Apple: `2024-04-26T08:35:26+00:00 Notice Your domain has been verified with Apple Pay!`.

The only thing that stands out is that the domain association file (https://support2enhance.co.uk/.well-known/apple-developer-merchantid-domain-association) is loaded on the browser instead of being offered for download, but their host has said this is normal.

The issue persists even in conflict test conditions with only WooCommerce, Square, and Storefront running on the merchant's site. My site works as expected though.

We've discussed this with Quark on Slack and have been advised to open a new issue - p1715329230051709-slack-C7U3Y3VMY.

**Screenshots**

What's showing:
Screen Shot 2024-05-14 at 11 22 36

### Expected behavior
The site should offer both Apple Pay and Google Pay since express checkouts have been enabled, and there are no errors with Apple Pay itself.
Screen Shot on 2024-05-14 at 11:42:07

**Environment (please complete the following information):**
 - WordPress Version: 6.5.2
 - WooCommerce Version: 8.8.2
 - WooCommerce Square Plugin Version: 4.6.1
 - Browser [e.g. chrome, safari] and Version: Version 15.6.1

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Fixes an issue in which the Apple Pay button was not displaying on the block cart and checkout pages for verified domains.

Closes #113

### Steps to test the changes in this Pull Request:

1. Install and configure the plugin on a publicly accessible site (ngrok works for local servers)
2. Configure the site to use block cart and checkout 
3. Log in to the Square dashboard
4. Download an add the domain verification file to the `/.well-known` directory of the site
5. Add the site's domain to the Apple Pay
6. Configure Square in the dashboard of WooCommerce
7. Enable Apple Pay/digital wallets
8. Create a simple product
9. In Safari go to the products page, ensure the Apple Pay button displays and allows you to purchase the product
10. Add the product to the cart
11. Visit the cart page, ensure the Apple Pay button displays and allows you to purchase the product
12. Add the product to the cart
13. Visit the checkout page, ensure the Apple Pay button displays and allows you to purchase the product
14. Configure the site to use shortcode cart and checkout
15. Add the product to the cart
16. Visit the cart page, ensure the Apple Pay button displays and allows you to purchase the product
17. Add the product to the cart
18. Visit the checkout page, ensure the Apple Pay button displays and allows you to purchase the product

Note: Geographical limitation prevent the use of Apple Pay in some countries.

### Changelog entry

> Fix - Apple Pay button is now available on Cart and Checkout Block pages.

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
5e6803754f89a7560844f2c386efa72fcbfe81e4 Resolves the issues we are seeing on the checkout (blocks) page. It appears that Apple Pay always returns the email address in the shipping contact details, even for virtual products. This triggers an error on the checkout page as the email address is required.

Darin's changes have fixed the display on the cart page but I'm still investigating what is triggering the processing failure.

**Review by peterwilsoncc — COMMENTED** [review]
@dkotter and I have both contributed code to this, as I opened the PR I can't hit approve but I am happy with his code.

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------

I have checked this issue in the `fix/113-apple-pay-blocks` branch and the related issue is resolved and working as expected.

I've tested Google Pay and as discussed internally @dkotter @peterwilsoncc has tested the apply pay, and it's working as expected.


I tested the following on this branch:
- Block checkout
- Shortcode checkout


**Testing Environment** 

<Details>

- WordPress: 6.5.4
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.2
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>


https://github.com/woocommerce/woocommerce-square/assets/67687255/076f64af-60eb-4ae7-9499-fe44d6d8e0d8



Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [ ] Yes
- [x] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Review by wjrosa — APPROVED** [review]
Code is good and works as expected:

1 - Product page
Screenshot 2024-06-06 at 19 36 50

2 - Cart block
Screenshot 2024-06-06 at 19 37 09

3 - Checkout block
Screenshot 2024-06-06 at 19 38 13

4 - Payment processing dialog
Screenshot 2024-06-06 at 19 39 02

5 - Cart shortcode
Screenshot 2024-06-06 at 19 44 42

6 - Checkout shortcode
Screenshot 2024-06-06 at 19 43 07

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.5.4
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.3
- PHP: 8.3.0
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: smoke-testing

</Details>

Next Step- Ready to Merge 🚀

**Pull request merged**
