### PR TITLE
Enhancement/E2E: Added some additional tests including tests related to subscriptions and pre-orders.

### LINKED ISSUE #118: Increase E2E test coverage
This supports the ability to ship releases more quickly and with greater confidence. The extension has end-to-end (E2E) tests and [covers more than 80% of the Critical Flows as documented in its GitHub Wiki](https://github.com/woocommerce/woocommerce-square/wiki/Critical-flows-WooCommerce-Square). This will aim to assess Critical Flows that are not yet covered by e2e tests and look to add those tests where feasible.

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [x] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
The PR adds some E2E tests from the critical flow to increase test coverage and also adds E2E tests for the subscriptions and pre-orders products.

Closes #118 

### Steps to test the changes in this Pull Request:
1. Verify E2E tests passing in GH action or in local

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by dkotter** [comment]
@iamdharmesh There are some merge conflicts here that need fixed. Can you take a look at those?

**Comment by iamdharmesh** [comment]
@dkotter Done. Some newly added tests are failing due to NUX changes, I will update it to fix it.

**Comment by iamdharmesh** [comment]
@dkotter Done.

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- The E2E test is passed, Working expected with Plugin Archive/Zip file same as fix specific branch.


Next Step- Ready to Merge 🚀

**Pull request merged**
