### PR TITLE
Update Square PHP SDK to v35

### LINKED ISSUE #33: Upgrade SDK version to 32.0.0.20231018
- [ ] Assess if there are any beneficial changes to Square with PHP SDK Version 32.0.0.20231018
- [ ] Upgrade the SDK version to 32.0.0.20231018

See: https://github.com/square/square-php-sdk/releases/tag/32.0.0.20231018

### LINKED ISSUE #69: [Spike] Upgrade Square SDK to version 35.0.0.20240222
### Describe the bug

https://github.com/square/square-php-sdk/releases/tag/35.0.0.20240222

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
PR updates the Square SDK from v29 to v35.

Closes #69 

### Steps to test the changes in this Pull Request:
As this is an upgrade to SDK full Regression testing is needed here (sync and all payment gateways).

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ❌
---

@iamdharmesh During testing, I notice some issues in the `smoke-testing` branch.

**Issue 1.** Unable to change payment method on the Subscription page. When attempting to update the payment method

1. Goto may account > Subscription
2. Select any subscription and change payment method

image

I also got a fatal error.

```
[09-Jun-2024 18:49:41 UTC] PHP Fatal error:  Uncaught Error: Call to a member function payment_method_supports() on false in /Users/sumitbagthariya/Local Sites/square/app/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-change-payment-gateway.php:423
Stack trace:
#0 /Users/sumitbagthariya/Local Sites/square/app/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-change-payment-gateway.php(373): WC_Subscriptions_Change_Payment_Gateway::update_all_payment_methods_from_subscription(Object(WC_Subscription), 'square_credit_c...')
#1 /Users/sumitbagthariya/Local Sites/square/app/public/wp-includes/class-wp-hook.php(324): WC_Subscriptions_Change_Payment_Gateway::change_payment_method_via_pay_shortcode('')
#2 /Users/sumitbagthariya/Local Sites/square/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /Users/sumitbagthariya/Local Sites/square/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /Users/sumitbagthariya/Local Sites/square/app/public/wp-settings.php(717): do_action('wp_loaded')
#5 /Users/sumitbagthariya/Local Sites/square/app/public/wp-config.php(114): require_once('/Users/sumitbag...')
#6 /Users/sumitbagthariya/Local Sites/square/app/public/wp-load.php(50): require_once('/Users/sumitbag...')
#7 /Users/sumitbagthariya/Local Sites/square/app/public/wp-blog-header.php(13): require_once('/Users/sumitbag...')
#8 /Users/sumitbagthariya/Local Sites/square/app/public/index.php(17): require('/Users/sumitbag...')
#9 {main}
  thrown in /Users/sumitbagthariya/Local Sites/square/app/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-change-payment-gateway.php on line 423
```

**Comment by iamdharmesh** [comment]
Thanks for checking on this @qasumitbagthariya. I think this issue is not related to this PR as I can reproduce this issue in the `trunk` branch as well. Could you please check this with `trunk` once? 

Thanks

**Comment by qasumitbagthariya** [comment]
> Thanks for checking on this @qasumitbagthariya. I think this issue is not related to this PR as I can reproduce this issue in the `trunk` branch as well. Could you please check this with `trunk` once?
> 
> Thanks

Cross check with the `trunk` branch, Create a separate issue [Square#150](https://github.com/woocommerce/woocommerce-square/issues/150)

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.5.4
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.3
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: smoke-testing

 </Details>


Next Step- Ready to Merge 🚀

**Pull request merged**
