### PR TITLE
fix/35: replace setDescription with setDescriptionHtml

### LINKED ISSUE #35: Products with long descriptions causing VALUE_TOO_LONG errors when attempting to sync
### Describe the bug

A merchant has shared a screenshot of an error they're getting when running a sync: 
image

I couldn't tell what field was that is causing the error however, I had a look over the Square API docs and found the catalog description has a 4096 limit so my guess is that it's probably this field: https://developer.squareup.com/reference/square/objects/CatalogItem

In our Square code, we set the [catalog description to the product description](https://github.com/woocommerce/woocommerce-square/blob/57f5ca735cfaed40dfb2ecee57659a807fd4cbaa/includes/Handlers/Product/Woo_SOR.php#L60C11-L60C11) without any character limit so I think we'll need to patch this line to limit the description to a maximum of 4096 characters.

From the Square docs, it looks like the description field has been deprecated in favour of the descriptionHTML field which has a 65535 limit, so maybe instead of setting a 4096 limit, maybe we should switch over to using [`setDescriptionHtml()`](https://github.com/square/square-php-sdk/blob/master/doc/models/catalog-item.md) instead:

image

### Expected behavior

Products with long descriptions in Woo are stripped when syncing over to Square to meet the Square API requirements.

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Closes #35 .

### Steps to test the changes in this Pull Request:

1. Add description in Woo product with more than 4096 characters and sync the product
2. Verify that description is visible in the response from the API explorer. Use the [list-catalog](https://developer.squareup.com/explorer/square/catalog-api/list-catalog) endpoint.

### Changelog entry

> Fix - Issue with syncing products with description more than 4096 characters.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ❌

-------------

In the sandbox dashboard, the problem remains unresolved since the `description` field continues to be trimmed down to 4096 characters. 


As discussed with @Sidsector9 this is the Square dashboard issue and we have requested the reopen the issue https://github.com/square/square-php-sdk/issues/127#issuecomment-1895072508


Video:

https://github.com/woocommerce/woocommerce-square/assets/67687255/19b31422-6741-40f2-b13a-078c952e04a2

**Review by qasumitbagthariya — COMMENTED** [review]
This PR is on hold until the issue is fixed from the square.

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------

I have checked this issue in the `fix/35` branch and the related issue is resolved and working as expected.

https://github.com/square/square-php-sdk/issues/127#issuecomment-1895072508 - Resolved

**Testing Environment** 

<Details>

- WordPress: 6.4.2
- Theme: Storefront 4.5.3
- WooCommerce - 8.5.1
- PHP: 8.0.21
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>

Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)


https://github.com/woocommerce/woocommerce-square/assets/67687255/42f2b8b6-4a5a-49fa-9a90-4c58a401aa57


Status update:
@ankitguptaindia

**Review by a-danae — APPROVED** [review]
Things look good to me 👍 

✅ I added a description with a length of 5000 characters. The sync was successful in this branch, while it failed in trunk with a `[VALUE_TOO_LONG] Field must not be greater than 4096 length` error message.

Thanks for the changes here, @Sidsector9 !

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

**Testing Environment** 

<Details>

- WordPress: 6.4.2
- Theme: Storefront 4.5.4
- WooCommerce - 8.5.2
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: smoke-testing
</Details>

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

Next Step- Ready to Merge 🚀

Status update 
@ankitguptaindia @vikrampm1

**Pull request merged**
