### PR TITLE
fix/30: Prevent Gift Card image from being forced upon a site

### LINKED ISSUE #30: Gift Card image forced upon a site
### Describe the bug

I've some feedback on the default Gift Card placeholder image. On a site, even if not using gift cards, you get the [gift card placeholder](https://github.com/woocommerce/woocommerce-square/blob/57f5ca735cfaed40dfb2ecee57659a807fd4cbaa/includes/Gateway/Gift_Card.php#L104C1-L104C1) image forced into your media library.

This has caused some merchants to worry there was a security issue on their site with a random image appearing. Especially since it's not clear from the image where it came from, and you can't delete it. That seems very suspicious from that perspective.

### To reproduce

1. Activate Square
2. Look in media library
3. See placeholder image

**Screenshots**

Screenshot 2023-09-12 at 12 17 31 PM

### Expected behavior

I think there are two areas and things we could look to improve. First, If adding an image for a merchant, is there any way to make that clearer? Do we need explicit permission, or can we add more metadata to the image to make it clear where this came from?

Screenshot 2023-09-12 at 12 29 48 PM

Also, why can't the image being deleted. I mean, it can be deleted, but the linked to function above adds it right back. That seems to take away some control from the merchant, and can seem sketchy if you already don't know where this image is coming from.

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Earlier, we added the default git card placeholder image to the media library on `init` hook.
In this PR, we add to the media library when the **Gift card product placeholder image** setting is enabled and the settings are saved at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=gift_cards_pay`.

This PR also adds a provision to replace the default placeholder for gift card via the following UI:

Screenshot 2024-08-12 at 7 15 24 PM

Closes #30

### Steps to test the changes in this Pull Request:

1. Delete the gift card placeholder (the purple one shown above) from the media library.
2. Create 2 gift card products. One with the product image set, and another without.
3. Go to `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=gift_cards_pay` and enable **Gift card product placeholder image** and save it.
4. Observe that the gift card placeholder gets added to the media library.
5. Observe that the gift card product created without the product image shows the purple image as the default placeholder.
6. Repeat (3) but this time replace the default placeholder.
7. Repeat (5) but this time observe the default placeholder is updated with whatever image you've set.
8. Delete the current active placeholder from the media library.
9. Observe that the setting **Gift card product placeholder image** automatically gets disabled.
10. Observe that the default placeholder for the gift card product is set to the image provided by Woo Core.

### Changelog entry

> Fix - Prevent Gift Card image from being forced upon a site.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------

I have verified this PR in the `fix/30` branch, issue has been fixed and is functioning as intended.

I tested the following on this branch:
- Gift card product placeholder image
- Gift card without image
- Block cart and checkout
- Shortcode cart
- Order again

**Testing Environment** 

<Details>

- WordPress: 6.6.1
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - 9.1.4
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Branch: smoke-testing

</Details>


https://github.com/user-attachments/assets/497f339f-3274-46cd-a7fc-f8d4d3303fd3

https://github.com/user-attachments/assets/8806bd5e-244e-455e-b533-f43088fad7cc



Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [x] Yes
- [ ] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Review by diegocurbelo — CHANGES_REQUESTED** [review]
The changes look good, and It tests well.

We are using the hard-coded string `woocommerce_gift_cards_pay_settings` in several files, we should use the constant `SQUARE_PAYMENT_SETTINGS_OPTION_NAME` instead.

It's true that option names rarely change, but using constants makes navigating the code easier, and remove the risk of typos. 

I'm guessing we are not using it because of the long class name, if that's the case we can move it to `includes/Gateway/Gift_Card.php` class (or create a new one with a more descriptive name) so it's prettier:

- `WC_REST_Square_Gift_Cards_Settings_Controller::SQUARE_PAYMENT_SETTINGS_OPTION_NAME`

- `Gift_Card::SQUARE_PAYMENT_SETTINGS_OPTION_NAME`

**Comment by Sidsector9** [comment]
Makes sense @diegocurbelo 👍 
I've made the changes in [358beec](https://github.com/woocommerce/woocommerce-square/pull/198/commits/358beec2f656690b84389595e2c64eed29279f8e).

**Review by diegocurbelo — APPROVED** [review]
Thank you @Sidsector9, the changes look good 🚢

**Pull request merged**
