### PR TITLE
Add ESLint GitHub Action workflow and Fix eslint issues

### LINKED ISSUE #119: Set up and resolve issues with ESLint
ESLint is not configured as a GitHub Action. The extension contains ESLint configuration files (.eslintrc.js, .eslintignore). However, when running the npm script “npm run lint:js”, it gives an error about not being able to find the plugin “eslint-plugin-jest” instead of displaying ESLint results.  This aims to adding in a standard Woo ESLint GitHub Action and then slowly resolving any issues it highlights as this extension has ~12% of its code in JavaScript.

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
PR adds ESLint GitHub Action workflow to enforce ESLint rules on pull requests and also improves the codebase by resolving issues reported by ESLint.

Closes #119

### Steps to test the changes in this Pull Request:
1. Verify that ESLint Action runs on PR and reports issues properly. (eg: see logs [here](https://github.com/woocommerce/woocommerce-square/actions/runs/9159227000/job/25179164243))
1. Regression testing of the extension

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by dkotter** [comment]
@iamdharmesh Not related to this PR but curious on why the `needs: e2e testing` label isn't being removed and replaced with the success label. I know that works on other extensions, wondering if there's something we need to update in our E2E test workflow file to make that work?

**Comment by dkotter** [comment]
@qasumitbagthariya This can go to UAT once QA passes

**Comment by iamdharmesh** [comment]
> @iamdharmesh Not related to this PR but curious on why the needs: e2e testing label isn't being removed and replaced with the success label. I know that works on other extensions, wondering if there's something we need to update in our E2E test workflow file to make that work?

@dkotter This is not related to the workflow file. I suspect GITHUB_TOKEN doesn't have enough permission granted to 
 add/remove labels. Permission settings can be found at "`Repo Settings` > `Actions` > `General` > `Workflow permissions`". Could we please check with the WooCommerce team on this to update permission settings for us?
 
 Thank you.

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------

 I have checked this issue in the enhacement/119 branch and working as expected.


I tested the following on this branch:
- Checkout flow (credit card, Gift card, Cashapp)
- Block checkout
- Shortcode base checkout
- Sync
- Import product

**Testing Environment** 

<Details>

- WordPress: 6.5.3
- Theme: Storefront 4.5.5
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>

Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for UAT
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [ ] Yes
- [x] Not Required/Applicable for this PR

**Review by qasumitbagthariya — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.5.4
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.2
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: smoke-testing
- </Details>

Next Step- Ready to Merge 🚀

**Pull request merged**
