### PR TITLE
Release/4.4.1

### LINKED ISSUE #43: Release version 4.4.1
This issue is for tracking the 4.4.1 release. Target release date: **January 08 2024**

## Pre-release steps

- [x] Merge woocommerce/woocommerce-square-private#1165   
- [x] Merge woocommerce/woocommerce-square-private#1167   
- [x] Merge woocommerce/woocommerce-square-private#1171   
- [x] Merge woocommerce/woocommerce-square-private#1175   
- [x] Merge woocommerce/woocommerce-square-private#1173  
- [x] Merge woocommerce/woocommerce-square-private#1174 

## Release steps

- [x] Branch: Starting from `trunk`, cut a release branch named `release/4.4.1`
- [x] Version bump: Bump the version number in `woocommerce-square.php`, `package.json`, `package-lock.json` and `readme.txt` to 4.4.1. In `woocommerce-square.php` update both the plugin "Version:" property and the plugin `WC_SQUARE_VERSION` constant
- [x] Update `@since`: Find all new `@since x.x.x` / `@since n.e.x.t` lines and update those with the new version number, 4.4.1
- [x] Generate changelog: Locally, generate the changelog by running the following Woorelease command: `php woorelease.phar cl:generate --product_version=4.4.1 https://github.com/woocommerce/woocommerce-square/tree/trunk`. Ensure the changelog updates look correct
- [x] Update changelog: Take the changelog generated from the previous step and update the release PR with those changes, both in the `changelog.txt` file and `readme.txt` file
- [x] Open PR: Open a new PR against `trunk` from the release branch, `release/4.4.1`
- [x] Run tests: On this release PR, add the label `needs: qit default tests` and `needs: e2e testing`. This will trigger the default QIT tests (activation, API and E2E) and our E2E tests. Ensure these tests pass as well as all other applicable tests
- [x] Merge: Merge the release PR into `trunk`
- [x] Prepare ZIP: Prepare the zip by running Woorelease locally on the `trunk` branch: `php woorelease.phar build https://github.com/woocommerce/woocommerce-square/tree/trunk`. Make sure you are running the proper versions of `node`, `npm` and `composer` to ensure the built files are consistent across releases. Versions can be found in [`package.json`](https://github.com/woocommerce/woocommerce-square/blob/trunk/package.json)
- [x] Compare: Download the latest [released zip](https://github.com/woocommerce/woocommerce-square/releases) and then run a diff compare against the generated zip, ensuring all expected changes are there (and no unexpected changes)
- [x] Test ZIP: Take the ZIP generated from the previous step and test this locally, ensuring version numbers look correct, the changelog looks correct and the plugin installs and activates properly
- [x] Attach ZIP: Attach the ZIP to this issue and ping the Automattic team in the `#a8c-10up-woo-support` channel to complete the release

### PR DESCRIPTION
**Pull request by dkotter**
### Changes proposed in this Pull Request:

Version bump and prep for the 4.4.1 release

Closes #43 

### Steps to test the changes in this Pull Request:

Verify all file changes look accurate

### CODE REVIEW

**Comment by dkotter** [comment]
@vikrampm1 I can't run the QIT tests here because the environment secrets don't seem to be set up yet.

@Sidsector9 E2E tests were taking forever here so I eventually cancelled them. Wondering if this is due to the new repo or if something else is going on?

**Comment by vikrampm1** [comment]
@dkotter got it. @iamdharmesh do you know if the environment secrets were set up by us or the Woo team in the previous repo? I remember you adding some secrets during e2e tests implementation, so can these be added by us in the same way?

**Comment by Sidsector9** [comment]
I've just set the keys for this repo. Running the tests again.

**Comment by vikrampm1** [comment]
@dkotter if the tests are running fine here then we can also aim to get this one out on January 16.

**Comment by dkotter** [comment]
> @dkotter if the tests are running fine here then we can also aim to get this one out on January 16.

This is ready to go though note QIT is still not set up to run here so we've not been able to verify those tests

**Review by vikrampm1 — APPROVED** [review]

**Pull request merged**
