### PR TITLE
Bump WooCommerce "tested up to" version 9.5 

### LINKED ISSUE #236: Compatibility testing with Woo 9.5 Beta
The goal for this task is to test WooCommerce 9.5 Beta compatibility with detailed steps noted below:

- [ ] Bump WooCommerce “WC Tested up to” to version 9.5 in plugin.php and GitHub Actions (if applicable).
- [ ] Bump WooCommerce “WC requires at least” to version 9.3 (as this matches the expected L-2 support policy) in plugin.php and GitHub Actions (if applicable).
- [ ] Check/Bump WordPress “Requires at least” to version 6.5 (to match the [WP minimum in WC 9.3](https://github.com/woocommerce/woocommerce/blob/9.3.0/plugins/woocommerce/readme.txt) in plugin.php and GitHub Actions (if applicable)).
- [ ] Check/Bump PHP “Requires PHP” to version 7.4 (to match the [PHP minimum in WC 9.3](https://github.com/woocommerce/woocommerce/blob/9.3.0/plugins/woocommerce/readme.txt) in plugin.php and GitHub Actions (if applicable)).
- [ ] Check other files where the version needs to be bumped - For this the main thing to look for is the function `version_compare` and then see if we're checking WC versions there or something else. Some plugins also define what WC version we support (sometimes as a minimum) in a constant (see [Square](https://github.com/woocommerce/woocommerce-square/blob/trunk/woocommerce-square.php#L55) as an example). There's not always consistent naming on those constants so really the easiest way to find these is to search the codebase for the version string. Search the last few releases to catch them all. Also, suggest looking at the last PR that bumped versions to copy what was done for those.
- [ ] Check if the following needs to be updated: `MINIMUM_PHP_VERSION`, `MINIMUM_WP_VERSION`, `MINIMUM_WC_VERSION`
- [ ] Scan for any conditional checks that may be in the code that can be removed with these “Tested up to” and minimum/"Requires" bumps.
- [ ] Add compatibility fixes, where necessary
- [ ] If e2e tests pass then move the issue to UAT. If e2e tests fail, see if that's an issue with the test or compatibility with WC.

After bumping versions in a PR, we will ensure that e2e tests and overall plugin functionality continues to work as expected via regression testing following [defined critical flows](https://github.com/woocommerce/woocommerce-square/wiki/Critical-flows-WooCommerce-Square) (if plugin functional compatibility changes were required).

Project success metrics:

- [ ] PR(s) merged to trunk
- [ ] Release ZIP created and tagged for release

Sample Changelog entry could then be:

> Dev - Bump WooCommerce "tested up to" version 9.5.
> Dev - Bump WooCommerce minimum supported version to 9.3.
> Dev - Bump WordPress minimum supported version to 6.5.
> Dev - Bump PHP minimum supported version to 7.4.

### PR DESCRIPTION
**Pull request by qasumitbagthariya**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Closes #236 

### Steps to test the changes in this Pull Request:

1. Run the e2e test using GitHub action to test compatibility
2. All tests should be passed.

### Changelog entry

> Dev - Bump WooCommerce "tested up to" version 9.5.
> Dev - Bump WooCommerce minimum supported version to 9.3.

### CODE REVIEW

**Comment by iamdharmesh** [comment]
**Update:** 

I have made changes to the E2E tests to accommodate the UI changes in WC 9.5, but the E2E tests related to Cash App Pay are still failing. Upon further investigation, I discovered that Cash App Pay is not working on mobile devices when using Block Checkout in WC 9.5-Beta-1. I have reported a separate issue(https://github.com/woocommerce/woocommerce-square/issues/241) to address this and will continue on this once the Cash App Pay issue on mobile devices is resolved. Thank you.

**Comment by iamdharmesh** [comment]
The WooCommerce Team has decided to revert the PR causing issues with the Cash App Pay on mobile, we should wait for the RC release and run the tests on it again.

**Comment by jeffpaul** [comment]
@qasumitbagthariya note that Woo 9.5 RC 1 is set for today, so please check back here first thing tomorrow to see if that's been released and if you can re-test here.

**Comment by iamdharmesh** [comment]
I have reverted changes I have made in E2E tests for WC 9.5 and with WC 9.5 - BETA-2 tests are passing now. So, we are ready for the next steps here. 

cc: @vikrampm1 @jeffpaul

**Review by dkotter — APPROVED** [review]

**Pull request merged**
