### PR TITLE
Replace the use of deprecated hook `wcs_renewal_order_meta` with `wc_subscriptions_renewal_order_data`

### LINKED ISSUE #179: The 'wcs_renewal_order_meta' filter is deprecated
### Describe the bug

Stores with Square and Subscriptions running currently get the following deprecated notice:

```
PHP Deprecated:  Hook wcs_renewal_order_meta is deprecated since version wcs-core 2.5.0! Use wc_subscriptions_renewal_order_data instead. in /public/wp-includes/functions.php on line 6078
```

From my search, Square still uses the `wcs_renewal_order_meta` hook here: https://github.com/woocommerce/woocommerce-square/blob/414e4126291bd85efdbae37c34890cd574491a6c/includes/Framework/PaymentGateway/Integrations/Payment_Gateway_Integration_Subscriptions.php#L96

We should update this hook to the new one `wc_subscriptions_renewal_order_data`. There will need to be minor changes as the form of the passed data is slightly different.

### To reproduce

1. Install and enable WooCommerce Subscriptions
1. Create a subscription product"
    - **Products > Add new**.
    - Select "Simple Subscription".
    - Enter a price.
    - Save.
1. Purchase the subscription using Square.
2. On the admin dashboard go to **WooCommerce > Subscriptions.**
3. From the actions drop down select "Process renewal".

<p align="center">
Screenshot 2024-07-17 at 2 50 11 PM
</p> 

6. Save the subscription to run the action.
7. Check your error logs, you should see the following notice:

```
PHP Deprecated:  Hook wcs_renewal_order_meta is <strong>deprecated</strong> since version wcs-core 2.5.0! Use wc_subscriptions_renewal_order_data instead. in /app/public/wp-includes/functions.php on line 6085
```

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
PR makes a minor change to replace the deprecated hook `wcs_renewal_order_meta` with `wc_subscriptions_renewal_order_data`

Closes #179

### Steps to test the changes in this Pull Request:
Detailed steps are given in the issue #179 description, Please verify that no deprecated notice is there in the error logs.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------

I have verified this PR in the `fix/179` branch has been fixed and is functioning as intended.

I tested the following on this branch:
- I can't reproduce with block checkout, but also able to reproduce the issue with shortcode base checkout
- Renewal orders

**Testing Environment** 

<Details>

- WordPress: 6.6.1
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - 9.1.4
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Branch: `fix/179`

</Details>


Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [ ] Yes
- [x] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Comment by vikrampm1** [comment]
@Mayisha this PR is ready for your review!

**Review by Mayisha — APPROVED** [review]
Thanks for the fix. Confirming that `wc_subscriptions_renewal_order_data` is being called during a subscription renewal.

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.6.1
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - 9.1.4
- WooCommerce Subscription - 6.5.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Branch: smoke-testing

</Details>


Next Step- Ready to Merge 🚀

**Pull request merged**
