### PR TITLE
Stop requesting to Reconnect to Square

### LINKED ISSUE #205: Changing environment selection from Sandbox to Production asks merchants to connect to Square even when already connected
### Describe the bug

When the Environment selection in the Square settings is changed from Sandbox to Production, you are asked to connect to Square even when already connected. This is confusing as some merchants try connecting to Square only to keep seeing the same thing.

### To reproduce
1. Update Squate to the latest version.
2. Go to Square settings under WooCommerce > Settings > Square.
3. Change the environment selection to Sandbox and save.
4. Change the environment selection to production and you'll see the connect to Square button. However, when you save it changes to "Disconnect from Square".

**Screenshots**

Screencast: https://d.pr/i/HzDfGP

### Expected behavior

If the site is already connected to Square the button should show "Disconnect from Square" when production is selected in the environment selection option instead of "Connect to Square".

### LINKED ISSUE #218: Update "Connect to Square" Settings
Currently, when a user changes the environment from Sandbox to Production (after the connection for Production was already established) it is still showing the button as “Connect to Square” which is inaccurate connection status. The setting should be updated with the following:

- [ ]  When a user switches from sandbox to production and we have previously stored connection details, then show a “Disconnect from Square” button instead of a “Connect to Square” button.
- [ ] When a user switches from sandbox to production and we don't have those details, then show the "Connect to Square” button instead.
- [ ]  Add a popup dialogue box that says “There are unsaved changes. Are you sure you want to leave this page” with “Cancel” and “Leave” buttons when the user tries to move away from the page without saving the changes to the environment selection.

### PR DESCRIPTION
**Pull request by faisal-alvi**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Closes #205 & Closes #218.

### Steps to test the changes in this Pull Request:

1. Navigate to the Square settings under **WooCommerce > Settings > Square**.
2. Switch the environment to **Production** and save the changes (skip if already connected to Prod).
3. Next, change the environment to **Sandbox** but do not save, switch it back to **Production**.
4. In the `trunk` branch, you'll notice the button "Connect to Square," which is incorrect because we are already connected to the Production environment.
5. In this PR branch, you will see the correct button, "Disconnect from Square."
6. Confirm it also fixes #218.

### Changelog entry

> Fix - Connection settings now persist previous connection when toggling between Production and Sandbox.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by faisal-alvi** [comment]
Update: Fixes for #218 are also added.

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ✅  

-------------

I have verified this PR in the `fix/205` branch which has been fixed and is functioning as intended.

I tested the following on this branch:
https://github.com/woocommerce/woocommerce-square/issues/205 
https://github.com/woocommerce/woocommerce-square/issues/218.

**Testing Environment** 

<Details>

- WordPress: 6.6.2
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - 9.2.3
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Branch: fix/205

</Details>


https://github.com/user-attachments/assets/64196504-7395-426c-9b63-8375da3c02f0



Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [ ] Yes
- [x] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Review by jeffpaul — APPROVED** [review]

**Review by Mayisha — APPROVED** [review]
Changes look good and it's working as described 👍 

**In `trunk`**
- Displays 'Connect to Square'  button even when the account is connected.
Screenshot 2024-09-19 at 1 28 26 AM


**In `fix/205`**
- Displays 'Disconnect from Square' button for connected account.
Screenshot 2024-09-19 at 1 32 29 AM

- Displays 'Connect to Square' button when the account is not connected.
Screenshot 2024-09-19 at 1 34 20 AM

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.


Next Step- Ready to Merge 🚀

**Pull request merged**
